// AUTH
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


// USER
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const UPDATE_CURRENT_USER_SUCCESS = 'UPDATE_CURRENT_USER_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


// DATEBOOK
export const ADD_DATEBOOK_SUCCESS = 'ADD_DATEBOOK_SUCCESS'
export const GET_ALL_DATEBOOKS_SUCCESS = 'GET_ALL_DATEBOOKS_SUCCESS'
export const GET_DATEBOOK_SUCCESS = 'GET_DATEBOOK_SUCCESS'